version: "3"

services:
  php:
    container_name: "${PROJECT_NAME}-php"
    build: ./.docker/php-fpm
    volumes:
      - ./src/status:/projects/status
    ports:
      - "9000:9000"

  nginx:
    container_name: "${PROJECT_NAME}-nginx"
    build: ./.docker/nginx
    ports:
      - 8080:80
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - ./src/status:/projects/status
      - ./src/wpfrp:/projects/wpfrp
    links:
        - php

  mysql:
    container_name: "${PROJECT_NAME}-mysql"
    build: ./.docker/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
