version: "3"

services:
  redis:
    container_name: "${PROJECT_NAME}-redis"
    build: ./.docker/redis
    ports:
      - "6379:6379"
    volumes:
      - "./artifacts/redis:/data"

  php:
    container_name: "${PROJECT_NAME}-php"
    build: ./.docker/php-fpm
    volumes:
      - "${PROJECT_ROOT}:/projects"
      - "./src/status:/usr/share/nginx/html"
    ports:
      - "9000:9000"
    links:
      - redis

  nginx:
    container_name: "${PROJECT_NAME}-nginx"
    build: ./.docker/nginx
    ports:
      - 8080:80
    volumes:
      - "./.docker/nginx/conf.d:/etc/nginx/conf.d"
      - "./src/status:/usr/share/nginx/html"
      - "${PROJECT_ROOT}:/projects"
    links:
      - php

  mysql:
    container_name: "${PROJECT_NAME}-mysql"
    build: ./.docker/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
