version: "3"

services:
  web:
    container_name: "${PROJECT_NAME}-web-server"
    build: ./dockerfiles/web-server
    # links:
    #   - "db-mongo:db-mongo"
    #   - "db-mysql:db-mysql"
    ports:
      - 8080:80

  db:
    container_name: "${PROJECT_NAME}-db-server"
    build: ./dockerfiles/database-server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
